# Generated by Django 5.1.6 on 2025-02-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriosProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200)),
                ('dificuldade', models.CharField(choices=[('lembrar', 'Lembrar'), ('entender', 'Entender'), ('aplicar', 'Aplicar'), ('analisar', 'Analisar'), ('avaliar', 'Avaliar'), ('criar', 'Criar')], default='lembrar', max_length=20)),
                ('quantidade_questoes', models.PositiveIntegerField()),
                ('tipos_questoes', models.CharField(choices=[('multipla_escolha', 'Múltipla Escolha'), ('dissertativa', 'Dissertativa'), ('verdadeiro_falso', 'Verdadeiro/Falso')], max_length=100)),
                ('curriculo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gabarito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostas', models.JSONField()),
                ('prova', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gabarito', to='provas.criteriosprova')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('multipla_escolha', 'Múltipla Escolha'), ('dissertativa', 'Dissertativa'), ('verdadeiro_falso', 'Verdadeiro/Falso')], max_length=20)),
                ('enunciado', models.TextField()),
                ('opcoes', models.JSONField(blank=True, null=True)),
                ('resposta', models.TextField()),
                ('nivel_dificuldade', models.CharField(blank=True, choices=[('lembrar', 'Lembrar'), ('entender', 'Entender'), ('aplicar', 'Aplicar'), ('analisar', 'Analisar'), ('avaliar', 'Avaliar'), ('criar', 'Criar')], default='lembrar', max_length=20, null=True)),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='provas.criteriosprova')),
            ],
        ),
    ]
